apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: privatemesh
resources:
  - namespace.yaml
  - runtime.yaml
  - coordinator.yaml
  - search-node-a.yaml
  - search-node-b.yaml
  - web.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: privatemesh
    includeSelectors: false
